### ISSUE TITLE
Issue on Mac only

### ISSUE THREAD

**Issue by ankitrox** [imakewebthings/jquery-waypoints#1]
When using mac track-pad and scrolling up, due to browser effect ( which causes scrollTop() position to be in negative ) the effect automatically appears even though the target element is not under viewport.

**Comment by imakewebthings** [comment]
You have opened this issue on the wrong repository. Please see https://github.com/imakewebthings/waypoints, read the [Contributing Guidelines](https://github.com/imakewebthings/waypoints/blob/master/CONTRIBUTING.md), and open an issue there with relevant code and links.
